"""feature2

Revision ID: 12ad7e5fc865
Revises: 57ed1227a4fc
Create Date: 2019-07-25 16:06:56.989914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ad7e5fc865'
down_revision = '57ed1227a4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_account', sa.Column('state', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_account', 'state')
    # ### end Alembic commands ###
