"""empty message

Revision ID: 448cf32072c4
Revises: 
Create Date: 2019-07-25 12:26:06.931062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448cf32072c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address1', sa.String(length=100), nullable=True),
    sa.Column('address2', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cutoff', sa.SmallInteger(), nullable=True),
    sa.Column('max_lead_time', sa.SmallInteger(), nullable=True),
    sa.Column('length_of_stay', sa.SmallInteger(), nullable=True),
    sa.Column('min_room_allotment', sa.SmallInteger(), nullable=True),
    sa.Column('max_room_allotment', sa.SmallInteger(), nullable=True),
    sa.Column('min_occupancy', sa.SmallInteger(), nullable=True),
    sa.Column('max_occupancy', sa.SmallInteger(), nullable=True),
    sa.Column('booking_counter', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conditions', schema='public')
    op.drop_table('client_accounts', schema='public')
    # ### end Alembic commands ###
