"""empty message

Revision ID: 57f81d268842
Revises: 448cf32072c4
Create Date: 2019-07-25 12:46:24.717609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f81d268842'
down_revision = '448cf32072c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_accounts', sa.Column('address3', sa.String(length=100), nullable=True))
    op.drop_column('client_accounts', 'address2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_accounts', sa.Column('address2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('client_accounts', 'address3')
    # ### end Alembic commands ###
