"""Test Jony

Revision ID: a2a47e51eb54
Revises: 448cf32072c4
Create Date: 2019-07-25 12:49:14.130518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a47e51eb54'
down_revision = '448cf32072c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.drop_column('client_accounts', 'state')
    op.add_column('conditions', sa.Column('custom', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conditions', 'custom')
    op.add_column('client_accounts', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_table('test_table', schema='public')
    # ### end Alembic commands ###
