"""empty message

Revision ID: c1ee818127f3
Revises: 57ed1227a4fc
Create Date: 2019-07-25 16:10:50.518832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ee818127f3'
down_revision = '57ed1227a4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address1', sa.String(length=100), nullable=True),
    sa.Column('address3', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('modelss',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address3', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.drop_table('client_account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_account',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('address1', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address3', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='client_account_pkey')
    )
    op.drop_table('modelss', schema='public')
    op.drop_table('client_accounts', schema='public')
    # ### end Alembic commands ###
